### 1. Imports

In [1]:
import pandas as pd
import numpy as np

### 2. Reading data

In [2]:
df = pd.read_csv("../data/players_cleaned.csv")

### 3. Dataset Overview

In [3]:
df.describe()

,level_1,Rank,Passes,Passes Completed,Passing Accuracy (%),Crosses,Crossing Accuracy (%),Take-Ons Completed,Defensive Linebreaks Attempted,Defensive Linebreaks Acc (%),...,Receptions In Behind,Receptions Between Midfield And Defensive Line,Receptions Under Pressure,Player Involvements,Top Speed (km/h),High Speed Running,Sprints,Total Distance (m),Goal Contribution,Goal Efficiency
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,...,400.000000,400.000000,400.000000,400.000000,400.000000,400.0000,400.000000,400.000000,400.00000,400.000000
mean,24.500000,21.902500,103.505000,95.425000,22.980000,1.790000,3.485000,0.645000,2.420000,13.705000,...,0.892500,9.230000,15.672500,85.150000,4.429675,41.0275,18.362500,4138.971475,1.26750,0.051355
std,14.448942,14.023896,186.473405,172.877271,39.905774,6.553111,11.973646,2.480798,5.663372,26.985524,...,3.313365,28.824977,44.373108,244.137985,11.736818,121.6615,54.716504,12358.236401,4.48064,0.168767
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.00000,0.000000
25%,12.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.00000,0.000000
50%,24.500000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.00000,0.000000
75%,37.000000,34.000000,74.250000,59.000000,19.500000,0.000000,0.000000,0.000000,0.250000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.00000,0.000000
max,49.000000,50.000000,799.000000,747.000000,97.000000,46.000000,100.000000,25.000000,36.000000,100.000000,...,33.000000,224.000000,258.000000,1676.000000,37.610000,787.0000,340.000000,73611.380000,45.00000,1.000000

### 4. Mean

In [4]:
df.mean(numeric_only=True)

level_1                                             24.500000
Rank                                                21.902500
Passes                                             103.505000
Passes Completed                                    95.425000
Passing Accuracy (%)                                22.980000
Crosses                                              1.790000
Crossing Accuracy (%)                                3.485000
Take-Ons Completed                                   0.645000
Defensive Linebreaks Attempted                       2.420000
Defensive Linebreaks Acc (%)                        13.705000
Switches of Play Attempted                           0.990000
Switches of Play Acc (%)                            21.320000
Assists                                              0.267500
Attempts On Target                                   0.402500
Attempts At Goal                                     1.000000
Attempts At Goal Conv. Rate (%)                      1.680000
Attempts Inside the Penalty Area                     0.630000
Attempts Outside the Penalty Area                    0.370000
Headed Attempts at Goal                              0.077500
xG                                                   0.123600
xG Efficiency                                        0.151475
Corners                                              0.592500
Own Goals                                            0.035000
Forced Turnovers                                     0.765000
Defensive Pressures Applied                          5.537500
Defensive Pressures Directly Applied                 0.922500
Fouls Against                                        1.167500
Fouls For                                            0.717500
Yellow Cards                                         0.095000
Red Cards                                            0.005000
Indirect Red Cards                                   0.005000
Offsides                                             0.105000
Goalkeeper Saves                                     1.582500
Goalkeeper Actions Inside the Penalty Area           9.657500
Goalkeeper Actions Outside the Penalty Area          8.145000
Offers To Receive                                   36.550000
Offers In Behind                                     9.052500
Offers In Between                                   15.007500
Offers In Front                                     12.490000
Offers Inside Team Shape                            21.407500
Offers Outside Team Shape                           15.142500
Receptions In Behind                                 0.892500
Receptions Between Midfield And Defensive Line       9.230000
Receptions Under Pressure                           15.672500
Player Involvements                                 85.150000
Top Speed (km/h)                                     4.429675
High Speed Running                                  41.027500
Sprints                                             18.362500
Total Distance (m)                                4138.971475
Goal Contribution                                    1.267500
Goal Efficiency                                      0.051355
dtype: float64

### 5. Median

In [5]:
df.median(numeric_only=True)

level_1                                           24.5
Rank                                              17.0
Passes                                             0.0
Passes Completed                                   0.0
Passing Accuracy (%)                               0.0
Crosses                                            0.0
Crossing Accuracy (%)                              0.0
Take-Ons Completed                                 0.0
Defensive Linebreaks Attempted                     0.0
Defensive Linebreaks Acc (%)                       0.0
Switches of Play Attempted                         0.0
Switches of Play Acc (%)                           0.0
Assists                                            0.0
Attempts On Target                                 0.0
Attempts At Goal                                   0.0
Attempts At Goal Conv. Rate (%)                    0.0
Attempts Inside the Penalty Area                   0.0
Attempts Outside the Penalty Area                  0.0
Headed Attempts at Goal                            0.0
xG                                                 0.0
xG Efficiency                                      0.0
Corners                                            0.0
Own Goals                                          0.0
Forced Turnovers                                   0.0
Defensive Pressures Applied                        0.0
Defensive Pressures Directly Applied               0.0
Fouls Against                                      0.0
Fouls For                                          0.0
Yellow Cards                                       0.0
Red Cards                                          0.0
Indirect Red Cards                                 0.0
Offsides                                           0.0
Goalkeeper Saves                                   0.0
Goalkeeper Actions Inside the Penalty Area         0.0
Goalkeeper Actions Outside the Penalty Area        0.0
Offers To Receive                                  0.0
Offers In Behind                                   0.0
Offers In Between                                  0.0
Offers In Front                                    0.0
Offers Inside Team Shape                           0.0
Offers Outside Team Shape                          0.0
Receptions In Behind                               0.0
Receptions Between Midfield And Defensive Line     0.0
Receptions Under Pressure                          0.0
Player Involvements                                0.0
Top Speed (km/h)                                   0.0
High Speed Running                                 0.0
Sprints                                            0.0
Total Distance (m)                                 0.0
Goal Contribution                                  0.0
Goal Efficiency                                    0.0
dtype: float64

### 6. Mode

In [6]:
df.mode(numeric_only=True).iloc[0]

level_1                                            0.0
Rank                                              14.0
Passes                                             0.0
Passes Completed                                   0.0
Passing Accuracy (%)                               0.0
Crosses                                            0.0
Crossing Accuracy (%)                              0.0
Take-Ons Completed                                 0.0
Defensive Linebreaks Attempted                     0.0
Defensive Linebreaks Acc (%)                       0.0
Switches of Play Attempted                         0.0
Switches of Play Acc (%)                           0.0
Assists                                            0.0
Attempts On Target                                 0.0
Attempts At Goal                                   0.0
Attempts At Goal Conv. Rate (%)                    0.0
Attempts Inside the Penalty Area                   0.0
Attempts Outside the Penalty Area                  0.0
Headed Attempts at Goal                            0.0
xG                                                 0.0
xG Efficiency                                      0.0
Corners                                            0.0
Own Goals                                          0.0
Forced Turnovers                                   0.0
Defensive Pressures Applied                        0.0
Defensive Pressures Directly Applied               0.0
Fouls Against                                      0.0
Fouls For                                          0.0
Yellow Cards                                       0.0
Red Cards                                          0.0
Indirect Red Cards                                 0.0
Offsides                                           0.0
Goalkeeper Saves                                   0.0
Goalkeeper Actions Inside the Penalty Area         0.0
Goalkeeper Actions Outside the Penalty Area        0.0
Offers To Receive                                  0.0
Offers In Behind                                   0.0
Offers In Between                                  0.0
Offers In Front                                    0.0
Offers Inside Team Shape                           0.0
Offers Outside Team Shape                          0.0
Receptions In Behind                               0.0
Receptions Between Midfield And Defensive Line     0.0
Receptions Under Pressure                          0.0
Player Involvements                                0.0
Top Speed (km/h)                                   0.0
High Speed Running                                 0.0
Sprints                                            0.0
Total Distance (m)                                 0.0
Goal Contribution                                  0.0
Goal Efficiency                                    0.0
Name: 0, dtype: float64

### 7. Standard Deviation

In [7]:
df.std(numeric_only=True)

level_1                                              14.448942
Rank                                                 14.023896
Passes                                              186.473405
Passes Completed                                    172.877271
Passing Accuracy (%)                                 39.905774
Crosses                                               6.553111
Crossing Accuracy (%)                                11.973646
Take-Ons Completed                                    2.480798
Defensive Linebreaks Attempted                        5.663372
Defensive Linebreaks Acc (%)                         26.985524
Switches of Play Attempted                            2.322366
Switches of Play Acc (%)                             39.883761
Assists                                               0.814003
Attempts On Target                                    1.836826
Attempts At Goal                                      3.814627
Attempts At Goal Conv. Rate (%)                       8.001416
Attempts Inside the Penalty Area                      2.403652
Attempts Outside the Penalty Area                     1.588840
Headed Attempts at Goal                               0.341739
xG                                                    0.572793
xG Efficiency                                         0.835584
Corners                                               3.415495
Own Goals                                             0.197160
Forced Turnovers                                      3.054193
Defensive Pressures Applied                          20.544434
Defensive Pressures Directly Applied                  3.511027
Fouls Against                                         3.174845
Fouls For                                             2.437735
Yellow Cards                                          0.355374
Red Cards                                             0.070622
Indirect Red Cards                                    0.070622
Offsides                                              0.561036
Goalkeeper Saves                                      4.553573
Goalkeeper Actions Inside the Penalty Area           27.601264
Goalkeeper Actions Outside the Penalty Area          23.205068
Offers To Receive                                    99.386754
Offers In Behind                                     28.956276
Offers In Between                                    41.892181
Offers In Front                                      39.618733
Offers Inside Team Shape                             61.584886
Offers Outside Team Shape                            44.000025
Receptions In Behind                                  3.313365
Receptions Between Midfield And Defensive Line       28.824977
Receptions Under Pressure                            44.373108
Player Involvements                                 244.137985
Top Speed (km/h)                                     11.736818
High Speed Running                                  121.661500
Sprints                                              54.716504
Total Distance (m)                                12358.236401
Goal Contribution                                     4.480640
Goal Efficiency                                       0.168767
dtype: float64

### 8. Variance

In [8]:
df.var(numeric_only=True)

level_1                                           2.087719e+02
Rank                                              1.966697e+02
Passes                                            3.477233e+04
Passes Completed                                  2.988655e+04
Passing Accuracy (%)                              1.592471e+03
Crosses                                           4.294326e+01
Crossing Accuracy (%)                             1.433682e+02
Take-Ons Completed                                6.154361e+00
Defensive Linebreaks Attempted                    3.207378e+01
Defensive Linebreaks Acc (%)                      7.282185e+02
Switches of Play Attempted                        5.393383e+00
Switches of Play Acc (%)                          1.590714e+03
Assists                                           6.626003e-01
Attempts On Target                                3.373929e+00
Attempts At Goal                                  1.455138e+01
Attempts At Goal Conv. Rate (%)                   6.402266e+01
Attempts Inside the Penalty Area                  5.777544e+00
Attempts Outside the Penalty Area                 2.524411e+00
Headed Attempts at Goal                           1.167857e-01
xG                                                3.280913e-01
xG Efficiency                                     6.982001e-01
Corners                                           1.166561e+01
Own Goals                                         3.887218e-02
Forced Turnovers                                  9.328095e+00
Defensive Pressures Applied                       4.220738e+02
Defensive Pressures Directly Applied              1.232731e+01
Fouls Against                                     1.007964e+01
Fouls For                                         5.942550e+00
Yellow Cards                                      1.262907e-01
Red Cards                                         4.987469e-03
Indirect Red Cards                                4.987469e-03
Offsides                                          3.147619e-01
Goalkeeper Saves                                  2.073503e+01
Goalkeeper Actions Inside the Penalty Area        7.618298e+02
Goalkeeper Actions Outside the Penalty Area       5.384752e+02
Offers To Receive                                 9.877727e+03
Offers In Behind                                  8.384659e+02
Offers In Between                                 1.754955e+03
Offers In Front                                   1.569644e+03
Offers Inside Team Shape                          3.792698e+03
Offers Outside Team Shape                         1.936002e+03
Receptions In Behind                              1.097839e+01
Receptions Between Midfield And Defensive Line    8.308793e+02
Receptions Under Pressure                         1.968973e+03
Player Involvements                               5.960336e+04
Top Speed (km/h)                                  1.377529e+02
High Speed Running                                1.480152e+04
Sprints                                           2.993896e+03
Total Distance (m)                                1.527260e+08
Goal Contribution                                 2.007613e+01
Goal Efficiency                                   2.848236e-02
dtype: float64

### 9. Minimum

In [9]:
df.min(numeric_only=True)

level_1                                           0.0
Rank                                              1.0
Passes                                            0.0
Passes Completed                                  0.0
Passing Accuracy (%)                              0.0
Crosses                                           0.0
Crossing Accuracy (%)                             0.0
Take-Ons Completed                                0.0
Defensive Linebreaks Attempted                    0.0
Defensive Linebreaks Acc (%)                      0.0
Switches of Play Attempted                        0.0
Switches of Play Acc (%)                          0.0
Assists                                           0.0
Attempts On Target                                0.0
Attempts At Goal                                  0.0
Attempts At Goal Conv. Rate (%)                   0.0
Attempts Inside the Penalty Area                  0.0
Attempts Outside the Penalty Area                 0.0
Headed Attempts at Goal                           0.0
xG                                                0.0
xG Efficiency                                     0.0
Corners                                           0.0
Own Goals                                         0.0
Forced Turnovers                                  0.0
Defensive Pressures Applied                       0.0
Defensive Pressures Directly Applied              0.0
Fouls Against                                     0.0
Fouls For                                         0.0
Yellow Cards                                      0.0
Red Cards                                         0.0
Indirect Red Cards                                0.0
Offsides                                          0.0
Goalkeeper Saves                                  0.0
Goalkeeper Actions Inside the Penalty Area        0.0
Goalkeeper Actions Outside the Penalty Area       0.0
Offers To Receive                                 0.0
Offers In Behind                                  0.0
Offers In Between                                 0.0
Offers In Front                                   0.0
Offers Inside Team Shape                          0.0
Offers Outside Team Shape                         0.0
Receptions In Behind                              0.0
Receptions Between Midfield And Defensive Line    0.0
Receptions Under Pressure                         0.0
Player Involvements                               0.0
Top Speed (km/h)                                  0.0
High Speed Running                                0.0
Sprints                                           0.0
Total Distance (m)                                0.0
Goal Contribution                                 0.0
Goal Efficiency                                   0.0
dtype: float64

### 10. Maximum

In [10]:
df.max(numeric_only=True)

level_1                                              49.00
Rank                                                 50.00
Passes                                              799.00
Passes Completed                                    747.00
Passing Accuracy (%)                                 97.00
Crosses                                              46.00
Crossing Accuracy (%)                               100.00
Take-Ons Completed                                   25.00
Defensive Linebreaks Attempted                       36.00
Defensive Linebreaks Acc (%)                        100.00
Switches of Play Attempted                           11.00
Switches of Play Acc (%)                            100.00
Assists                                               7.00
Attempts On Target                                   23.00
Attempts At Goal                                     41.00
Attempts At Goal Conv. Rate (%)                     100.00
Attempts Inside the Penalty Area                     27.00
Attempts Outside the Penalty Area                    19.00
Headed Attempts at Goal                               2.00
xG                                                    6.54
xG Efficiency                                        12.33
Corners                                              38.00
Own Goals                                             2.00
Forced Turnovers                                     32.00
Defensive Pressures Applied                         180.00
Defensive Pressures Directly Applied                 28.00
Fouls Against                                        15.00
Fouls For                                            17.00
Yellow Cards                                          2.00
Red Cards                                             1.00
Indirect Red Cards                                    1.00
Offsides                                              7.00
Goalkeeper Saves                                     28.00
Goalkeeper Actions Inside the Penalty Area          141.00
Goalkeeper Actions Outside the Penalty Area         124.00
Offers To Receive                                   485.00
Offers In Behind                                    191.00
Offers In Between                                   258.00
Offers In Front                                     287.00
Offers Inside Team Shape                            367.00
Offers Outside Team Shape                           322.00
Receptions In Behind                                 33.00
Receptions Between Midfield And Defensive Line      224.00
Receptions Under Pressure                           258.00
Player Involvements                                1676.00
Top Speed (km/h)                                     37.61
High Speed Running                                  787.00
Sprints                                             340.00
Total Distance (m)                                73611.38
Goal Contribution                                    45.00
Goal Efficiency                                       1.00
dtype: float64

### 11. Percentiles

In [11]:
df.quantile([0.25, 0.50, 0.75], numeric_only=True)

,level_1,Rank,Passes,Passes Completed,Passing Accuracy (%),Crosses,Crossing Accuracy (%),Take-Ons Completed,Defensive Linebreaks Attempted,Defensive Linebreaks Acc (%),...,Receptions In Behind,Receptions Between Midfield And Defensive Line,Receptions Under Pressure,Player Involvements,Top Speed (km/h),High Speed Running,Sprints,Total Distance (m),Goal Contribution,Goal Efficiency
0.25,12.0,13.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.50,24.5,17.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.75,37.0,34.0,74.25,59.0,19.5,0.0,0.0,0.0,0.25,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 12. Top 10 Goal Contributions

In [12]:
df[["Player", "Goal Contribution"]].sort_values(
    by="Goal Contribution",
    ascending=False
).head(10)

              Player  Goal Contribution
52     Kylian Mbappe               45.0
55      Lionel Messi               39.0
50     Michael Olise               27.0
76   Ousmane Dembele               22.0
72  Leandro Trossard               19.0
96      Ismaila Sarr               18.0
82     Achraf Hakimi               16.0
60       Bukayo Saka               16.0
65         Dani Olmo               15.0
67   Viktor Gyokeres               14.0

### 13. Top 10 Assists

In [13]:
df[["Player", "Assists"]].sort_values(
    by="Assists",
    ascending=False
).head(10)

              Player  Assists
50     Michael Olise      7.0
51   Martin Odegaard      4.0
52     Kylian Mbappe      4.0
53       Brahim Diaz      4.0
54   Bruno Guimaraes      4.0
55      Lionel Messi      4.0
61    Alexander Isak      3.0
56  Roberto Alvarado      3.0
57    Anthony Gordon      3.0
58     Florian Wirtz      3.0

### 14. Top 10 Attempts at Goal

In [14]:
df[["Player", "Attempts At Goal"]].sort_values(
    by="Attempts At Goal",
    ascending=False
).head(10)

              Player  Attempts At Goal
52     Kylian Mbappe              41.0
55      Lionel Messi              35.0
50     Michael Olise              20.0
76   Ousmane Dembele              20.0
96      Ismaila Sarr              17.0
72  Leandro Trossard              17.0
82     Achraf Hakimi              14.0
60       Bukayo Saka              13.0
65         Dani Olmo              13.0
67   Viktor Gyokeres              12.0

### 15. Top 10 Passes

In [15]:
df[["Player", "Passes"]].sort_values(
    by="Passes",
    ascending=False
).head(10)

              Player  Passes
100            Rodri   799.0
0              Rodri   799.0
1        Pau Cubarsi   690.0
101      Pau Cubarsi   690.0
2    Aymeric Laporte   660.0
102  Aymeric Laporte   660.0
103  Leandro Paredes   565.0
3    Leandro Paredes   565.0
4         Marc Guehi   532.0
104       Marc Guehi   532.0

### 16. Top 10 Top Speed

In [16]:
df[["Player", "Top Speed (km/h)"]].sort_values(
    by="Top Speed (km/h)",
    ascending=False
).head(10)

                 Player  Top Speed (km/h)
350       Kylian Mbappe             37.61
351      Anthony Elanga             37.16
352    Micky Van De Ven             36.77
353          Jordan Bos             36.67
354      Erling Haaland             36.52
355  Abdukodir Khusanov             36.46
356     Bradley Barcola             36.32
357         Djed Spence             36.22
358      Theo Hernandez             36.17
359       Nelson Semedo             35.90